services:
  app:
    build:
      context: .
    container_name: art2landing
    restart: always
    ports:
      - 3001:3000
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
