import styles from '../styles.module.scss'
import cn from 'classnames'

export const SectionPrivacyPolicy = () => {
  return (
    <section id={'privacy-policy'} className={cn(styles.wrapper, 'section')}>
      <div className={styles.content}>
        <h2 className={cn(styles.title, 'h1 mb-12')}>Privacy Policy</h2>

        <h3 className={cn(styles.title, 'body3 mb-24')}>
          Update 2024 - 06 - 24
        </h3>

        <p className={'body3 mb-24'}>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
          <br />
          <br />
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy
        </p>

        <h3 className={cn(styles.title, 'mb-24')}>
          Interpretation and Definitions
        </h3>

        <h3 className={cn(styles.accent, 'mb-12')}>Interpretation</h3>

        <p className={'body3 mb-24'}>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className={cn(styles.accent, 'mb-12')}>Definitions</h3>

        <p className={'body3 mb-24'}>
          For the purposes of this Privacy Policy:
          <br />
          <br />
          Account means a unique account created for You to access our Service
          or parts of our Service.
          <br />
          <br />
          Affiliate means an entity that controls, is controlled by or is under
          common control with a party, where "control" means ownership of 50% or
          more of the shares, equity interest or other securities entitled to
          vote for election of directors or other managing authority.
          <br />
          <br />
          Application means the software program provided by the Company
          downloaded by You on any electronic device, named ArtSqrd.
          <br />
          <br />
          Device means any device that can access the Service such as a
          computer, a cellphone or a digital tablet.
          <br />
          <br />
          Personal Data is any information that relates to an identified or
          identifiable individual.
          <br />
          <br />
          Service refers to the Application.
          <br />
          Service Provider means any natural or legal person who processes the
          data on behalf of the Company. It refers to third-party companies or
          individuals employed by the Company to facilitate the Service, to
          provide the Service on behalf of the Company, to perform services
          related to the Service or to assist the Company in analyzing how the
          Service is used.
          <br />
          <br />
          Usage Data refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for
          example, the duration of a page visit).
          <br />
          <br />
          You means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable.
        </p>
      </div>
    </section>
  )
}
